// This file is automatically generated. Do not modify it manually.
import { FirebaseOptions } from 'firebase/app';

// The following fields are sourced from your Firebase project.
export const firebaseConfig: FirebaseOptions = {
  apiKey: "AIzaSyDzdFVeAZ9y8ThHMAmSR3qXka01m1J9yJs",
  authDomain: "studio-8177975468-5ff33.firebaseapp.com",
  projectId: "studio-8177975468-5ff33",
  appId: "1:636084667049:web:2b5dec9a22b5a280131fb8",
  messagingSenderId: "636084667049"
};
